version: "2.4"
services:
  pihole:
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole
    volumes:
      - "./pihole/:/etc/pihole/"
      - "./dnsmasq.d/:/etc/dnsmasq.d/"
    environment:
      - ServerIP=${IP}
      #      - ServerIPv6=${IPv6}
      - DNS1=${DNS1}
      - DNS2=${DNS2}
      - TZ=Europe/Berlin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
